# Generated by Django 4.2.13 on 2024-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('service_id', models.UUIDField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('service_description', models.CharField(blank=True, max_length=200, null=True)),
                ('service_duration_hrs', models.FloatField()),
            ],
        ),
    ]
