# Generated by Django 4.2.13 on 2024-07-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_cost',
            field=models.FloatField(default=0),
        ),
    ]
